# Generated by Django 6.0.3 on 2026-03-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account_number',
            new_name='account_no',
        ),
    ]
